### ISSUE TITLE
Firefox plugin auto-update link is dead

### ISSUE THREAD

**Issue by MarHaj** [getreu/pandoc-notetaking#2]
The link to Firefox plugin [auto-reload](https://addons.mozilla.org/en-US/firefox/addon/auto-reload/) referenced in **documentations** and **pandoc-note script** is dead.

**Comment by getreu** [comment]
Yes, indeed. Have you found a replacement? Maybe [Tab Auto Refresh – Get this Extension for 🦊 Firefox (en-US)](https://addons.mozilla.org/en-US/firefox/addon/tab-auto-refresh/)?

**Comment by MarHaj** [comment]
I did indeed. [Auto Reload Tab](https://addons.mozilla.org/en-US/firefox/addon/auto-reload-tab/) works for me perfectly - during reload doesn't scroll the page.

**Comment by getreu** [comment]
Done. Thank you!
